# Generated by Django 3.0.4 on 2020-04-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_detail_uuid',
            new_name='questions_uuid',
        ),
    ]
