# Generated by Django 3.0.4 on 2020-04-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20200402_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='questions_uuid',
            field=models.CharField(max_length=24),
        ),
    ]
