# Generated by Django 3.0.4 on 2020-04-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20200402_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='questions_uuid',
            new_name='questions_id',
        ),
    ]
