# Generated by Django 3.0.4 on 2020-04-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_vote_answers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='answers_id',
            new_name='voting_results_id',
        ),
    ]
