# Generated by Django 3.0.5 on 2020-04-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_auto_20200409_1118'),
        ('votes', '0006_vote_voting_results_id'),
    ]

    operations = [
    ]
