# Generated by Django 3.0.5 on 2020-04-26 06:16

from django.db import migrations, models
import votes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0008_merge_20200426_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='closing_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='description',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='tags',
            field=models.CharField(default='', max_length=65, validators=[votes.validators.validate_tags]),
            preserve_default=False,
        ),
    ]
