# Generated by Django 3.0.5 on 2020-04-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0009_auto_20200426_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
