"""
Django settings for suguvote_root project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import bcrypt
from distutils.util import strtobool

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from suguvote_root.mongodb_connector import MongoDBConnector

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(strtobool(os.environ.get('DJANGO_DEBUG', 'False')))

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    SECRET_KEY = 'qp_4u!*w4=htnxk$34$)7qamn4jj$ygz+vk9in2th*epo$27o1'
else:
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

RECAPTCHA_SECRET_KEY = os.environ.get('DJANGO_RECAPTCHA_SECRET_KEY')


# ALLOWED_HOSTS
if DEBUG:
    ALLOWED_HOSTS = [
        '*'
    ]
else:
    ALLOWED_HOSTS = [
        'api.suguvote.net'
    ]

# CORS_ORIGIN
if DEBUG:
    CORS_ORIGIN_WHITELIST = [
        'http://192.168.0.3:8000'
    ]
else:
    CORS_ORIGIN_WHITELIST = [
        "https://www.suguvote.net"
    ]

# CORS_ALLOW_CREDENTIALS
CORS_ALLOW_CREDENTIALS = True

# Set session cookie secure
if DEBUG:
    SESSION_COOKIE_SECURE = False
else:
    SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'suguvote.apps.SuguvoteConfig',
    'users',
    'votes',
    'authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'suguvote_root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'suguvote_root.wsgi.application'

# Sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MARIADB_SUGUVOTE_DB_NAME', 'suguvote'),
        'USER': os.environ.get('MARIADB_SUGUVOTE_USERNAME', 'root'),
        'PASSWORD': os.environ.get('MARIADB_SUGUVOTE_PASSWORD', ''),
        'HOST': os.environ.get('MARIADB_SUGUVOTE_HOST', 'localhost'),
        'PORT': os.environ.get('MARIADB_SUGUVOTE_PORT', 3306),
        'ATOMIC_REQUESTS': True
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ja-jp'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# Caches
if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': 'unix:/tmp/memcached.sock',
        }
    }


AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication'
    ],
    'DEFAULT_PAGINATION_CLASS': 'suguvote_root.pagination.SuguvoteDefaultPagination',
}
if DEBUG:
    pass
else:
    REST_FRAMEWORK.update({
        'DEFAULT_RENDERER_CLASSES': (
            'rest_framework.renderers.JSONRenderer',
        )
    })

BCRYPT_SALT = bcrypt.gensalt(rounds=12, prefix=b'2a')

MONGODB_CONNECTOR =MongoDBConnector(
    db_name=os.environ.get('MONGODB_SUGUVOTE_DB_NAME', 'suguvote'),
    db_user=os.environ.get('MONGODB_SUGUVOTE_USERNAME', ''),
    db_password=os.environ.get('MONGODB_SUGUVOTE_PASSWORD', ''),
    host=os.environ.get('MONGODB_SUGUVOTE_HOST', 'localhost'),
    port=os.environ.get('MONGODB_SUGUVOTE_PORT', 27017),
    using_auth=bool(strtobool(os.environ.get('MONGODB_SUGUVOTE_USING_AUTH', 'True')))
)

# Consts.
MAX_TAG_LENGTH = 12
MAX_TAG_COUNT = 5
SESSION_ID_TAG = 'sess_id'